openapi: 3.0.0
info:
  title: Code Improve API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 1.0.0

servers:
  - url: http://localhost:30007

paths:
  /api/v1/createPermission:
    post:
      summary: Create the permission
      description: Create a new permission in the system.
      tags:
        - PermissionController
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: number
                  description: The userId of the user.
                roleId:
                  type: number
                  description: The roleId of the user
                name:
                  type: string
                  description: the name of the permission
                description:
                  type: string
                  description: the description of the permission
              
              required:
                - userId
                - roleId
                - name
                - description
      responses:
        201:
          description: Permission created successfully.
        400:
          description: Invalid request data.
        500:
          description: An error occurred while creating the permission.

  /api/v1/getPermission:
    get:
      summary: getting all of the permission
      description: getting all of the permission.
      tags:
        - PermissionController
      responses:
        201:
          description: Permission created successfully.
        400:
          description: Invalid request data.
        500:
          description: An error occurred while creating the permission.

  /api/v1/deletePermission:
    post:
      summary: deletion of the permission
      description: deletion of the permission.
      tags:
        - PermissionController
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                roleId:
                   type: number
                   description: the roleId of the user
                userId:
                   type: number
                   description: the userId of the user
                name:
                  type: string
                  description: The name of the user
              required:
                - roleId
                - userId
                - name
      responses:
        200:
          description: Permission deleted successfully.
        401:
          description: Unable to delete the permission.

  /api/v1/updatePermission:
    post:
      summary: to update the permission
      description: to update the permission.
      tags:
        - PermissionController
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                roleId:
                   type: number
                   description: the roleId of the user
                userId:
                   type: number
                   description: the userId of the user
                name:
                  type: string
                  description: The name of the user
                description:
                  type: string
                  description: the description of the permission
              required:
                - roleId
                - userId
                - name
                - description
     
      responses:
        200:
          description: permission updated successfully.
        401:
          description: Unable to update.

  